-- Configuration for mason-lspconfig.nvim
-- This file is automatically generated with mason generate
-- Bridges mason.nvim with lspconfig.nvim using both together

local opts = {
	ensure_installed = {
		"angularls",
		"efm",
		"bashls",
		"ts_ls",
		"tailwindcss",
		"pyright",
		"lua_ls",
		"emmet_ls",
		"jsonls",
	},

	automatic_installation = true,
}

return {
	"williamboman/mason-lspconfig.nvim",
	event = "BufReadPre",
	dependencies = "williamboman/mason.nvim",
}
